#!/bin/bash

run_and_die() {
    echo "[$1] running ..."
    $1
    rc=$?
    if [[ $rc -ne 0 ]]; then
        echo "[$1] FAILED"
        exit $rc
    fi
    echo "[$1] OK"
}

#run_and_die "php artisan code:analyse --level=5"
run_and_die "vendor/bin/phpcbf --standard=phpcs.xml app"
run_and_die "vendor/bin/phpcs --standard=phpcs.xml app"
